### ISSUE TITLE
Unsuccessful JPEG2000 creation shows as success in logs

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/iiif-image-scripts#82]
## Describe the bug
While running the pipeline over invalid TIFF files that cause JPG2000 creation to fail, the log file indicates that JPG2000 file creation was a success (`JPEG2000 derivatives with identifier VTQMDFDHAaEcbeFxcXJeQv created for ref_id 1e3d7bd7f64c45f2986c78f9c15f16c1`). In cases where no JPG2000 files were created because of invalid TIFF files, the log then shows the immediate failure at manifest creation.

When looking at the terminal output, it is clear that JPG2000 creation failed:
```
tiftoimage: Bad color format 3.
	Only RGB(A) and GRAY(A) has been implemented
	Aborting.
Unable to load tiff file
```

## To reproduce
Run the pipeline over TIFF files that cannot be processed by `tiftoimage`. Compare the log file to terminal output.

## Expected behavior
The log file would indicate when an error in JPG2000 creation results in the file not actually being created.

## Impact on your work
This caused confusion and delays in troubleshooting groups of TIFF files where none were valid. In a case where there is one invalid TIFF in a group of valid TIFFs, this might prevent a failed JPG2000 creation from being discovered.

**Comment by p-galligan** [comment]
Ok, so here's my thought process after looking at this issue:

There's just one message being logged here for each identifier, but we're raising individual exceptions for each file in `create_jp2`. But because we're iterating over a group of files in `create_jp2`, it's a little tricky to return just a true or false statement.

My thought process is to write any raised exceptions to a list in `create_jp2`, and then check if the variable set to `create_pdf(jp2_files, identifier, pdf_dir, replace)` is empty or not. From there we can have separate messages following that call in `pipeline.py` and log each individual error in the logs.

Does that make sense?

**Comment by helrond** [comment]
So @bonniegee should chime in since she's the one who discovered this issue, but I think this is really about the error message accurately reflecting the problem. Right now, the exception that gets thrown indicates there's a problem with manifest creation, but really the problem is in the previous stage, because JP2 creation wasn't successful.

My sense is that we would want to raise an exception when a single file isn't correctly converted to JP2 (rather than just returning a boolean). Ideally that exception would just bubble up to the exception handling in the main function, so it would get logged.

**Comment by bonniegee** [comment]
I would agree that what's most important here is making sure that if there's an error that prevents JPG2000 creation for a file, that error is written to the logs. I think that in any case where one file fails, even if all other files are properly converted, we want the whole unit to fail.

**Comment by helrond** [comment]
A bit more context as I (slowly) remember things:
- the root cause of this is that `subprocess.run()` won't throw an error if the command doesn't execute successfully. The fix might be as simple as throwing in a `check=True` (see [docs](https://docs.python.org/3/library/subprocess.html)) but you'd have to make sure that the return code from that command is not zero.
- I believe that this call originally used `subprocess.check_output()` but we moved away from that because it was gobbling up all available system memory. If that's true for the solution proposed above, it may be necessary to run the command and then do a secondary check to make sure that the file was actually created.
